import { Inter } from "next/font/google";
import Sidebar from "./(components)/sidebar";
import "./globals.css";
import { Container } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Container sx={{display:"flex", flexDirection:"row", height:"100dvh"}} disableGutters> 
          <Sidebar/>
          {children}
      </Container> 
      </body>
    </html>
  );
}
